# Generated by Django 6.1.1 on 2026-10-08 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshsession',
            name='device_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='refreshsession',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='refreshsession',
            name='user_agent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
